version: "3.1"
services:
    uka-db:
        build: ./mysql
        volumes:
            - ./mysql-data:/var/lib/mysql:cached
            - ./mysql-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
        environment:
            MYSQL_DATABASE: uka
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        tty: true
    uka-backend:
        build: ./app
        depends_on: 
            - uka-db
        links:
            - uka-db
        environment:
            UKA_DB_URL: uka-db/uka
            UKA_DB_USER: user
            UKA_DB_PASSWORD: password
            TZ: Japan
            JAVA_OPS: -Xmx512m -XX:TieredStopAtLevel=1
            SLEEP: 0
        ports:
            - "80:80"
        tty: true
