spring:
    datasource:
        url: jdbc:mysql://uka-db:3306/uka
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update

server:
    port: 80
    tomcat:
        accesslog:
            enabled: true
            directory: /var/log/tomcat
            pattern: "%t %D %s %h %l \"%r\" \"%{Referer}i\" \"%{User-Agent}i\" %b"