uka:
    version: 0.0.10
    callbackURL: "https://www.google.com" 

spring:
    datasource:
        url: jdbc:mysql://${UKA_DB_URL}?useSSL=false&allowPublicKeyRetrieval=true
        username: ${UKA_DB_USER}
        password: ${UKA_DB_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
    social:
        twitter:
            appId: ${UKA_TWITTER_ID}
            appSecret: ${UKA_TWITTER_SECRET}
        auto-conection-views: false

liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true

security:
    require-ssl: true
    basic:
        enabled: false

server:
    port: ${PORT:80}
    Tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto

logging:
    level:
        org:
            hibernate: ERROR
            springframework:
                web: DEBUG
