uka:
    version: 0.0.1

spring:
    datasource:
        url: jdbc:mysql://uka-db/uka
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update

server:
    port: ${PORT:8080}
    tomcat:
        accesslog:
            enabled: true
            directory: /var/log/tomcat
            pattern: "%t %D %s %h %l \"%r\" \"%{Referer}i\" \"%{User-Agent}i\" %b"