openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Uka
  license:
    name: MIT
servers:
  - url: http://{host}:{port}/api/v1
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '8080'
paths:
  /session:
    $ref: ./paths/session.yaml
  /trends:
    $ref: ./paths/trends.yaml
  /hit_log:
    $ref: ./paths/hit-log.yaml
  /users:
    $ref: ./paths/users.yaml
  /users/{user_id}:
    $ref: ./paths/users-from-id.yaml
  /ranking:
    $ref: ./paths/ranking.yaml
  /predict_words:
    $ref: ./paths/predict-words.yaml