name: test

on: push

jobs:
  app:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt install -y nodejs npm
        sudo npm install -g swagger-merger
        swagger-merger -i app/openapi/index.yaml -o app/openapi/merged.yaml

    - name: Test
      run: |
        cd app && ./mvnw test